/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hsbc;

import com.github.tomakehurst.wiremock.*;

public class App {
    public static void main(String[] args) {
        int port = 1080;
        System.out.println("Wiremock server started on port " + port);

        WireMockServer wireMockServer = new WireMockServer(port);
        wireMockServer.start();
    }
}
