/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hsbc;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        assertEquals(1, 1);
    }
}
